/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicRegisterRouteImport } from './routes/api/public/register'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRegisterRoute = ApiPublicRegisterRouteImport.update({
  id: '/api/public/register',
  path: '/api/public/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/verify' | '/welcome' | '/api/public/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/verify' | '/welcome' | '/api/public/register'
  id: '__root__' | '/' | '/verify' | '/welcome' | '/api/public/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VerifyRoute: typeof VerifyRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiPublicRegisterRoute: typeof ApiPublicRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/register': {
      id: '/api/public/register'
      path: '/api/public/register'
      fullPath: '/api/public/register'
      preLoaderRoute: typeof ApiPublicRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VerifyRoute: VerifyRoute,
  WelcomeRoute: WelcomeRoute,
  ApiPublicRegisterRoute: ApiPublicRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
